### ISSUE TITLE
Modlist Repository Issue 

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [Rage-GitHub/Fable-Lore#1]
Download property in modlists.json is a duplicate to your other list potentially causing issues.

other than that it is recommended to not make Multiple repositories (modlists.json files) and instead keep them all under one repository for all your lists. The documentation and readmes can be still separated for organization.

**Comment by Rage-GitHub** [comment]
Fixed modlists.json file for the appropriate information. Not going to consolidate each modlist into one repo just for organization sake.
