### ISSUE TITLE
TK Dodge RE is not installed correctly, will not show in Config Manager [BUG]

### ISSUE THREAD

**Issue by neomewilson** [Rage-GitHub/Fable-Lore#2]
## What Issue is Occurring?
*TK Dodge RE was added in the 1.20 release, it is missing the TK Dodge SE file*

## Where/When/How is This Issue Happening?
*I examined the .ini file that controls the dodge options for TK Dodge RE to reset some of the settings such as what key is used for dodge, etc. I launched the game and tried to dodge without success, I executed "setStage SKI_ConfigManagerInstance 1" to ensure it was added to the configuration manager menu as I did not see it there. It never showed up.

Afterwards I quit the game, found the TK Dodge RE documentation on Nexus and discovered you had not installed the TK Dodge SE file that is required of this to operate correctly. You can find a link to it under Requirements on the Description tab of TK Dodge RE. 

I installed the mod, read the install documentation and also discovered that the order should be 

Nemesis
TK Dodge SE
TK Dodge RE

After ensuring all of this was correct, I ran Nemesis Behavior Manager again, also because I am running Skyrim Paraglider I had to run it again to make sure it was added as the last item in the load inside of Nemesis Behavior Manager. Everything looked good so I restarted the game, executed the console command "setStage SKI_ConfigManagerInstance 1* again to force it to register in the MCM and reviewed the list and I could now see TK Dodge in the MCM. I configured it the way I wanted it, tested it afterwards and everything worked as expected.

## Have You Modified The Modlist In Anyway?
<sup>Select Only One Option, I.E. fill [ ] with an X as such "[X]"</sup>
- [ ] No, I have not touched the modlist
- [X] Yes, I've edited it somewhat
- [ ] Yes, I've made significant changes to the modlist

### If you've made changes, what mods/changes have you added/removed?
*
Creepy Zombies
Dovahkiin's Vault SSE
Fairies
Forgotten Magic Redone SE
Honed Metals
Kozakowy's Falka Armor UNP - SSE
Levelers Tower v4.4
Rigmor of Bruma - Reboot
Rigmor of Cyrodiil - Reboot
Rigmor of Cyrodiil Ayleid Addon White Marble SE
Rigmor of Cyrodiil Makeover
Shovels Bury Bodies
Skyrim's Paraglider
Skyshards
The Notice Board SE
Thunderchild

## Were You Able to Replicate This Issue?
<sup>Select Only One Option, I.E. fill [ ] with an X as such "[X]"</sup>
- [X] Yes, I've successfully replicated the issue
- [ ] No, it was a one-time thing

## Other Information
**Modlist Version**
> *relace me with your version of the modlist*

**Game Version**
> *1.20*

**Is The Modlist Installed on the Same Drive?**
<sup>Select Only One Option, I.E. fill [ ] with an X as such "[X]"</sup>
- [ ] Yes, it's installed in the same drive
- [X] No, it's installed on a different drive

**Is Your Game Installation Outside of Protected Folders, I.E. Program Files (x86)?**
<sup>Select Only One Option, I.E. fill [ ] with an X as such "[X]"</sup>
- [X] Yes, it's installed outside of a protected folder
- [ ] No, it's not installed outside of a protected folder

**What Are Your PC Specs?**
<sup>
OS: Windows 10 Home
Processor: 11th Gen Intel Core i7 - 11700K @ 3.60 Mhz, 8 Cores, 16 Logical Processors
Physical RAM: 64 GB RAM
Page File Space: 40.0 GB
Display Type: NVIDIA GetForce RTX 3070 TI
Hard Drives:
C Drive: 1 TB - Windows OS and supporting files
D Drive: 1 TB - Games Installed
E Drive:  2 TB - SSD Mod Packs
F Drive: 500GB - SSD - Development
G Drive: 3 TB - Physical Spindel - Backups
</sup>

**Comment by Rage-GitHub** [comment]
This is an issue on my part, I had included the wrong set of files and forgot to install them. I will be pushing out a update here soon for this.

**Comment by Rage-GitHub** [comment]
TK Dodge RE has been replaced with CGO's dodging method, since TK Dodge RE doesn't seem to want to work regardless of the installation being correct.
