### ISSUE TITLE
[REQUEST] Bloodchill Manor - Majestic Mountains and Enhanced Landscape Patch

### ISSUE THREAD

**Issue by JimTheGrackle** [Rage-GitHub/Fable-Lore#4]
Bloodchill Manor - Majestic Mountains and Enhanced Landscape Patch

The link is: [*paste mod link here*](https://www.nexusmods.com/skyrimspecialedition/mods/72618?tab=files)

Bloodchill Cavern/Manor is outright blocked otherwise

**Comment by Rage-GitHub** [comment]
Good catch, I will add this in the next update.

**Comment by Rage-GitHub** [comment]
Added within Version 1.4.1.
