### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by JimTheGrackle** [Rage-GitHub/Fable-Lore#5]
Beyond Skyrim Bruma -  Tweaks Enhancements and Patches SSE

## Does The Mod Reside on Nexus Mods?
[ ] Yes, the link is: (https://www.nexusmods.com/skyrimspecialedition/mods/19374?tab=files)

This mod will allow the creation of fur-plates via campfire for animals in Bruma/Cyrodil

**Comment by Rage-GitHub** [comment]
Added as of 1.10.0. Thanks for the suggestion!
